### PR TITLE
ci: update semantic release action to pull from ghcr

### PR DESCRIPTION
**Pull request by codfish**
Improves workflow run times by ~45s. Leverages changes here codfish/semantic-release-action#156

See codfish/semantic-release-action#142 for more context

### CODE REVIEW

**Comment by franky47** [comment]
Thanks for the PR! I'm going to try and pin it by hash, for extra security:
https://francoisbest.com/posts/2020/the-security-of-github-actions#docker-based-actions

**Comment by codfish** [comment]
@franky47 No problem! With docker images I don't think you're not gonna be able to handle that the same way I'm afraid. Since theyre just image tags they can be overwritten. But maybe ghcr supports some feature to try and tie it to a commit Sha 🤷‍♂️

**Comment by franky47** [comment]
Yes, I managed to pin it:

Workflow run (5s to pull! 🚀): https://github.com/47ng/fastify-micro/runs/1799691898
Syntax:
```yml
uses: docker://ghcr.io/codfish/semantic-release-action@sha256:16ab6c16b1bff6bebdbcc6cfc07dfafff49d23c6818490500b8edb3babfff29e
```

Now, to see if Dependabot will be able to pick it up and update it (it does on Git SHA1s).. 🤷‍♂️

**Comment by codfish** [comment]
@franky47 ahh nice! good to know, thanks. I responded without following your link and reading 😄 🤦

**Comment by franky47** [comment]
Hum it looks like Dependabot is not ready for GHCR updates yet, I got a ton of emails asking for authorization as it's looking for a ghcr.io/codfish repository, which does not exist:
https://app.dependabot.com/accounts/47ng/update-logs/65687579

That being said, I'm still using the Dependabot Preview in those repos, I'll see if migrating to the GitHub-built-in version solves the problem.

**Comment by codfish** [comment]
@franky47 how'd it go?

**Comment by franky47** [comment]
I haven't had the chance to release anything yet, I'll let you know when I do.

**Pull request merged**
